version: "3.8"
services:

  mysql:
    image: "mysql:latest"
    ports:
      - "23306:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "211010"
      MYSQL_DATABASE: "blueblog"
      MYSQL_PASSWORD: "211010"
    volumes:
      - ./init.sql:/data/application/init.sql

  redis:
    image: "redis:latest"
    ports:
      - "26379:6379"

  blueblog:
    build: .
    command: sh -c "./wait.sh mysql:3306 redis:6379 -- ./blueblog ./conf/config.yaml"
    depends_on:
      - mysql
      - redis
    ports:
      - "8888:8888"
