name: "blueblog"
mode: "dev"
port: 8080
version: "v0.0.1"
start_time: "2023-07-01"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "blueblog.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: localhost
  port: 13306
  user: "root"
  password: "211010"
  dbname: "blueblog"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: localhost
  port: 16379
  db: 0
  password: ""
  pool_size: 100
